### ISSUE TITLE
Wat is dit?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Metehan2003/the-client-website#1]
Zijn dit echt drie headers met divs erin?

https://github.com/Metehan2003/the-client-website/blob/085cbcdcd5b196a4041a32945a8073faede89312/index.html#L10-L20

**Comment by Metehan2003** [comment]
Ik zag dat de vierkanten na het gebruiken van headers te voorschijn kwamen van daar die headers maar nu ik ze heb weggehaald staan ze er nog steeds. Dus ik heb ze nu weggehaald.

**Comment by KrijnHoetmer** [comment]
Probeer je site eerst te maken zonder CSS, dus volledig in HTML. Dan focus je je meer op de structuur en semantiek, en wordt je HTML beter.

**Comment by Metehan2003** [comment]
Oké

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Krijn Hoetmer ***@***.***>
Verzonden: Friday, September 29, 2023 4:19:33 PM
Aan: Metehan2003/the-client-website ***@***.***>
CC: Metehan Şahin ***@***.***>; State change ***@***.***>
Onderwerp: Re: [Metehan2003/the-client-website] Wat is dit? (Issue #1)


Probeer je site eerst te maken zonder CSS, dus volledig in HTML. Dan focus je je meer op de structuur en semantiek, en wordt je HTML beter.
